export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const CALCULATE_MONTHLY_SALARY = "CALCULATE_SELFEMPLOYEE_SALARY";
export const CALCULATE_YEARLY_SALARY = "CALCULATE_YEARLY_SALARY";
export const SET_CALCULATION_TYPE = "SET_CALCULATIN_TYPE";

export const GET_DICTIONARIES = "GET_DICTIONARIES";
export const GET_MONTHNAME = "GET_MONTHNAME";

