version: '3.4'

services:
  sf.calculator.api:
    image: ${DOCKER_REGISTRY}calculatorapi
    build:
      context: .
      dockerfile: Calculator/SF.Calculator.API/Dockerfile
  postgresdb:
    image: postgres
    restart: always